version: "3.1"

services:
  postgress:
    image: 11.5
     restart: always
      environment: 
          - POSTGRESS_PASSWORD=pass123
          - POSTGRESS_DB=jira_development

      ports: 
          - 5432-5432
      networks:
          - shared-network
      volumes:
          - ./postgress.db:/var/lib/postgresql/data

api:
    container_name: jira_api
    
     restart: unless-stopped

    image: jira-api-prod:1.0.0

    build:
        context: api
        target: production
        dockerFile: 
      environment: 
          - POSTGRESS_PASSWORD=pass123
          - POSTGRESS_DB=jira_development
      ports: 
          - 3000-3000
      networks:
          - shared-network
        
      depends_on:
          - postgress

client:
    container_name: jira_client
    
    restart: unless-stopped

    image: jira-client-prod:1.0.0

    build:
        context: client
        target: production
        dockerFile: DockerFile
      ports: 
          - 8080-8081
      networks:
          - shared-network
        
      depends_on:
          - api

networks:
    shred-network:     


